### ISSUE TITLE
Why isnt it possible to change the height coordinate in this version of moveit?

### ISSUE THREAD

**Issue by haakonelf** [Hypha-ROS/hypharos_ardrone_navigation#11]
The title expalins it, but Im used to moveit also having the option of a wanted z-coordinate, but in rviz here, only the 2D ground plane axis are moveable on the model?

**Comment by haochihlin** [comment]
Hi
Well, this project was first implemented 5 years ago (my bachlor thesis).
In that period, because of time limits, we just assume the drone will only navigate in the 2D plane.
The height was defined by the state of drone directly.
So, if you want to control the height, you need to send command manually.
